In [1]:
import numpy as np 
import pandas as pd

# loading the dataset
df = pd.read_csv("bank-full.csv", sep=';')

# check the columns
df.columns


Index(['age', 'job', 'marital', 'education', 'default', 'balance', 'housing',
       'loan', 'contact', 'day', 'month', 'duration', 'campaign', 'pdays',
       'previous', 'poutcome', 'y'],
      dtype='object')

In [2]:
# check for null values
df.isna().sum()

age          0
job          0
marital      0
education    0
default      0
balance      0
housing      0
loan         0
contact      0
day          0
month        0
duration     0
campaign     0
pdays        0
previous     0
poutcome     0
y            0
dtype: int64

In [3]:
# separate the target variable from the features
X = df.drop(columns='y')
y = df['y'].map({'yes':1, "no":0})

# separating categorical and numerical features
categorical_features = X.select_dtypes(include=['object']).columns
numerical_features = X.select_dtypes(exclude=['object']).columns

# One-hot encoding for categorical features
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer

preprocessor = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), numerical_features),
        ('cat', OneHotEncoder(handle_unknown='ignore'), categorical_features)
         ]         )

print(numerical_features)
print(categorical_features)

Index(['age', 'balance', 'day', 'duration', 'campaign', 'pdays', 'previous'], dtype='object')
Index(['job', 'marital', 'education', 'default', 'housing', 'loan', 'contact',
       'month', 'poutcome'],
      dtype='object')


In [4]:
# splitting the data into training and testing sets
from sklearn.model_selection import train_test_split

X_train, X_test, y_train,y_test = train_test_split(X, y, test_size=0.2, random_state=42)

from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, roc_auc_score
from sklearn.pipeline import Pipeline 

# creating preprocesser for each model 
rf_preprocessor = ColumnTransformer([
    ('num', StandardScaler(), numerical_features),
    ('cat', OneHotEncoder(handle_unknown='ignore'), categorical_features)
])

svm_preprocessor = ColumnTransformer([
    ('num', StandardScaler(), numerical_features),
    ('cat', OneHotEncoder(handle_unknown='ignore'), categorical_features)
])

knn_preprocessor = ColumnTransformer([
    ('num', StandardScaler(), numerical_features),
    ('cat', OneHotEncoder(handle_unknown='ignore'), categorical_features)
])

# creating model pipelines
knn_model = Pipeline([
    ('preprocessor', knn_preprocessor),
    ("K nearest neighbors", KNeighborsClassifier(n_neighbors=5))
])

rf_model = Pipeline([
    ('preprocessor', rf_preprocessor),
    ("Random Forest", RandomForestClassifier(n_estimators=10, random_state=42))
])

svm_model = Pipeline([
    ('preprocessor', svm_preprocessor),
    ("Support Vector Machine", SVC(kernel='rbf', random_state=42))
])


In [5]:
# creating an ensemble model using stacking
from sklearn.ensemble import StackingClassifier
from sklearn.linear_model import LogisticRegression

estimators = [
    ('knn', knn_model),
    ('rf', rf_model),
    ('svm', svm_model)
]
final_estimator = LogisticRegression(class_weight='balanced', random_state=42, max_iter=1000)

stacking_model = StackingClassifier(
    estimators = estimators, 
    final_estimator= final_estimator,
    cv=5
)
# training the stacking model
stacking_model.fit(X_train, y_train)


StackingClassifier(cv=5,
                   estimators=[('knn',
                                Pipeline(steps=[('preprocessor',
                                                 ColumnTransformer(transformers=[('num',
                                                                                  StandardScaler(),
                                                                                  Index(['age', 'balance', 'day', 'duration', 'campaign', 'pdays', 'previous'], dtype='object')),
                                                                                 ('cat',
                                                                                  OneHotEncoder(handle_unknown='ignore'),
                                                                                  Index(['job', 'marital', 'education', 'default', 'housing', 'loan', 'contact',
       'month', 'pout...
                                                                                  Index(['age', 'balance', 'day', 'duration', 'campaign', 'pdays', 'previous'], dtype='object')),
                                                                                 ('cat',
                                                                                  OneHotEncoder(handle_unknown='ignore'),
                                                                                  Index(['job', 'marital', 'education', 'default', 'housing', 'loan', 'contact',
       'month', 'poutcome'],
      dtype='object'))])),
                                                ('Support Vector Machine',
                                                 SVC(random_state=42))]))],
                   final_estimator=LogisticRegression(class_weight='balanced',
                                                      max_iter=1000,
                                                      random_state=42))

In [6]:
# making predictions
y_pred = stacking_model.predict(X_test)

# evaluating the model
print("Accuracy", accuracy_score(y_test, y_pred))
print("Classification report\n", classification_report(y_test, y_pred))
print("Confusion matrix\n", confusion_matrix(y_test, y_pred))

Accuracy 0.8760367134800399
Classification report
               precision    recall  f1-score   support

           0       0.97      0.89      0.93      7952
           1       0.49      0.81      0.61      1091

    accuracy                           0.88      9043
   macro avg       0.73      0.85      0.77      9043
weighted avg       0.91      0.88      0.89      9043

Confusion matrix
 [[7042  910]
 [ 211  880]]


In [32]:
# permutation importance on the ensemble model
from sklearn.inspection import permutation_importance

pfi_ensemble = permutation_importance(stacking_model, X_test, y_test, n_repeats=5, random_state=42)

# creating a dataframe for the permutation importance results
pfi_ensmeble_df = pd.DataFrame({
    'feature': X_test.columns,
    'importance_mean': pfi_ensemble.importances_mean,
    'importance_std': pfi_ensemble.importances_std
}).sort_values(by='importance_mean', ascending=False)

pfi_ensmeble_df
pfi_ensmeble_df.head(5)

KeyboardInterrupt: 

In [8]:
import time 
t0 = time.time()
_ = stacking_model.predict(X_test)
print("Time taken for prediction:", time.time()- t0)

Time taken for prediction: 19.343682050704956


In [7]:
import matplotlib.pyplot as plt

plt.figure(figsize=(15,10))
plt.bar(pfi_ensmeble_df['feature'], pfi_ensmeble_df['importance_mean'], yerr=pfi_ensmeble_df['importance_std'])
plt.title("Permutation Feature Importance for Stacking Ensemble")
plt.ylabel("Performance Drop ")
plt.tight_layout()
plt.show()



NameError: name 'pfi_ensmeble_df' is not defined

<Figure size 1500x1000 with 0 Axes>

In [8]:
X_top5 = df[["month", "duration","contact","pdays","day"]]
y = df['y']

categorical_features = X_top5.select_dtypes(include=['object']).columns
numerical_features = X_top5.select_dtypes(exclude=['object']).columns


# train test split
X_top5_train, X_top5_test, y_train, y_test = train_test_split(X_top5, y, test_size=0.2, random_state=42)



preprocessor = ColumnTransformer([
    ('num', StandardScaler(), numerical_features),
    ('cat', OneHotEncoder(handle_unknown='ignore'), categorical_features)
])

# creating model pipelines
knn5_model = Pipeline([
    ('preprocessor', preprocessor),
    ("K nearest neighbors", KNeighborsClassifier(n_neighbors=5))
])

rf5_model = Pipeline([
    ('preprocessor', preprocessor),
    ("Random Forest", RandomForestClassifier(n_estimators=10, random_state=42))
])

svm5_model = Pipeline([
    ('preprocessor', preprocessor),
    ("Support Vector Machine", SVC(probability=True,kernel='rbf', random_state=42))
])

# stacking model
estimators5 = [
    ("knn5 model", knn5_model),
    ("svm5 model", svm5_model),
    ("rf5 model", rf5_model)
]
final_estimator5 = LogisticRegression(class_weight='balanced', random_state=42, max_iter=1000)

stacking_model5 = StackingClassifier(
    estimators = estimators5, 
    final_estimator= final_estimator5,
    cv=5
)
# training the stacking model
stacking_model5.fit(X_top5_train, y_train)



StackingClassifier(cv=5,
                   estimators=[('knn5 model',
                                Pipeline(steps=[('preprocessor',
                                                 ColumnTransformer(transformers=[('num',
                                                                                  StandardScaler(),
                                                                                  Index(['duration', 'pdays', 'day'], dtype='object')),
                                                                                 ('cat',
                                                                                  OneHotEncoder(handle_unknown='ignore'),
                                                                                  Index(['month', 'contact'], dtype='object'))])),
                                                ('K nearest neighbors',
                                                 KNeighborsClassifier())])),
                               ('svm5 model',
                                Pipeline(s...
                                                 ColumnTransformer(transformers=[('num',
                                                                                  StandardScaler(),
                                                                                  Index(['duration', 'pdays', 'day'], dtype='object')),
                                                                                 ('cat',
                                                                                  OneHotEncoder(handle_unknown='ignore'),
                                                                                  Index(['month', 'contact'], dtype='object'))])),
                                                ('Random Forest',
                                                 RandomForestClassifier(n_estimators=10,
                                                                        random_state=42))]))],
                   final_estimator=LogisticRegression(class_weight='balanced',
                                                      max_iter=1000,
                                                      random_state=42))

In [9]:
y_pred5 = stacking_model5.predict(X_top5_test)

In [10]:
# evaluation metrics
print("Accuracy: ", accuracy_score(y_test,y_pred5))
print("Classification report:\n ", classification_report(y_test, y_pred5))
print("Confusion matrix:\n ", confusion_matrix(y_test, y_pred5))
print("AUC: ", roc_auc_score(y_test,stacking_model5.predict_proba(X_top5_test)[:,1]))


Accuracy:  0.8775848722768993
Classification report:
                precision    recall  f1-score   support

          no       0.97      0.89      0.93      7952
         yes       0.50      0.77      0.60      1091

    accuracy                           0.88      9043
   macro avg       0.73      0.83      0.76      9043
weighted avg       0.91      0.88      0.89      9043

Confusion matrix:
  [[7099  853]
 [ 254  837]]
AUC:  0.9109336933608987


In [11]:
# ensemble ML + SVM 
svm5_model.fit(X_top5_train, y_train)

y_svm_pred = svm5_model.predict(X_top5_test)

# evaluation metrics 
print("Accuracy: ", accuracy_score(y_test,y_svm_pred))
print("Classification report:\n ", classification_report(y_test, y_svm_pred))
print("Confusion matrix:\n ", confusion_matrix(y_test, y_svm_pred))
print("AUC: ", roc_auc_score(y_test,svm5_model.predict_proba(X_top5_test)[:,1]))



Accuracy:  0.9043459029083268
Classification report:
                precision    recall  f1-score   support

          no       0.92      0.97      0.95      7952
         yes       0.68      0.39      0.50      1091

    accuracy                           0.90      9043
   macro avg       0.80      0.68      0.72      9043
weighted avg       0.89      0.90      0.89      9043

Confusion matrix:
  [[7752  200]
 [ 665  426]]
AUC:  0.8909768763820319


In [12]:
# ensemble ML + KNN
knn5_model.fit(X_top5_train, y_train)

y_knn_pred = knn5_model.predict(X_top5_test)

# evaluation metrics 
print("Accuracy: ", accuracy_score(y_test,y_knn_pred))
print("Classification report:\n ", classification_report(y_test, y_knn_pred))
print("Confusion matrix:\n ", confusion_matrix(y_test, y_knn_pred))
print("AUC: ", roc_auc_score(y_test,knn5_model.predict_proba(X_top5_test)[:,1]))

Accuracy:  0.898595598805706
Classification report:
                precision    recall  f1-score   support

          no       0.93      0.96      0.94      7952
         yes       0.60      0.46      0.52      1091

    accuracy                           0.90      9043
   macro avg       0.77      0.71      0.73      9043
weighted avg       0.89      0.90      0.89      9043

Confusion matrix:
  [[7621  331]
 [ 586  505]]
AUC:  0.8739025583381129


In [13]:
# ensemble ML + RF
rf5_model.fit(X_top5_train, y_train)

y_rf_pred = rf5_model.predict(X_top5_test)

# evaluation metrics 
print("Accuracy: ", accuracy_score(y_test,y_rf_pred))
print("Classification report:\n ", classification_report(y_test, y_rf_pred))
print("Confusion matrix:\n ", confusion_matrix(y_test, y_rf_pred))
print("AUC: ", roc_auc_score(y_test,rf5_model.predict_proba(X_top5_test)[:,1]))

Accuracy:  0.8917394669910428
Classification report:
                precision    recall  f1-score   support

          no       0.92      0.95      0.94      7952
         yes       0.57      0.43      0.49      1091

    accuracy                           0.89      9043
   macro avg       0.75      0.69      0.71      9043
weighted avg       0.88      0.89      0.89      9043

Confusion matrix:
  [[7593  359]
 [ 620  471]]
AUC:  0.8653423750569411


In [24]:
# ensemble XAI + ensemble

X_xai = df[['duration','month','poutcome','contact','day']]
y = df['y']

categorical_features =  X_xai.select_dtypes(include=['object']).columns
numerical_features = X_xai.select_dtypes(exclude=['object']).columns

X_xai_train, X_xai_test, y_train, y_test = train_test_split(X_xai, y, test_size=0.2, random_state=42)

preprocessor = ColumnTransformer([
    ('num', StandardScaler(), numerical_features),
    ('cat', OneHotEncoder(handle_unknown='ignore'), categorical_features)
])

knn_xai = Pipeline([
    ('preprocessor', preprocessor),
    ("K nearest neighbors", KNeighborsClassifier(n_neighbors=5))
])

rf_xai = Pipeline([
    ('preprocessor', preprocessor),
    ("Random Forest", RandomForestClassifier(n_estimators=10, random_state=42))
])

svm_xai = Pipeline([
    ('preprocessor', preprocessor),
    ("Support Vector Machine", SVC(probability=True,kernel='rbf', random_state=42))
])

# stacking model
estimators_xai = [
    ("knn5 model", knn_xai),
    ("svm5 model", svm_xai),
    ("rf5 model", rf_xai)
]
final_estimator_xai = LogisticRegression(class_weight='balanced', random_state=42, max_iter=1000)

stacking_model_xai = StackingClassifier(
    estimators = estimators_xai, 
    final_estimator= final_estimator_xai,
    cv=5
)
# training the stacking model
stacking_model_xai.fit(X_xai_train, y_train)


StackingClassifier(cv=5,
                   estimators=[('knn5 model',
                                Pipeline(steps=[('preprocessor',
                                                 ColumnTransformer(transformers=[('num',
                                                                                  StandardScaler(),
                                                                                  Index(['duration', 'day'], dtype='object')),
                                                                                 ('cat',
                                                                                  OneHotEncoder(handle_unknown='ignore'),
                                                                                  Index(['month', 'poutcome', 'contact'], dtype='object'))])),
                                                ('K nearest neighbors',
                                                 KNeighborsClassifier())])),
                               ('svm5 model',
                                Pipelin...
                                                 ColumnTransformer(transformers=[('num',
                                                                                  StandardScaler(),
                                                                                  Index(['duration', 'day'], dtype='object')),
                                                                                 ('cat',
                                                                                  OneHotEncoder(handle_unknown='ignore'),
                                                                                  Index(['month', 'poutcome', 'contact'], dtype='object'))])),
                                                ('Random Forest',
                                                 RandomForestClassifier(n_estimators=10,
                                                                        random_state=42))]))],
                   final_estimator=LogisticRegression(class_weight='balanced',
                                                      max_iter=1000,
                                                      random_state=42))

In [23]:
X_xai.columns

Index(['duration', 'month', 'poutcome', 'contact', 'day'], dtype='object')

In [25]:
y_xai_pred = stacking_model_xai.predict(X_xai_test)

In [26]:
print("Accuracy: ", accuracy_score(y_test,y_rf_pred))
print("Classification report:\n ", classification_report(y_test, y_rf_pred))
print("Confusion matrix:\n ", confusion_matrix(y_test, y_rf_pred))
print("AUC: ", roc_auc_score(y_test,rf5_model.predict_proba(X_top5_test)[:,1]))

Accuracy:  0.8917394669910428
Classification report:
                precision    recall  f1-score   support

          no       0.92      0.95      0.94      7952
         yes       0.57      0.43      0.49      1091

    accuracy                           0.89      9043
   macro avg       0.75      0.69      0.71      9043
weighted avg       0.88      0.89      0.89      9043

Confusion matrix:
  [[7593  359]
 [ 620  471]]
AUC:  0.8653423750569411
