In [1]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt

In [5]:
#clean data
df = pd.read_csv('bank-full.csv', sep=';')

#highest performance features Borda Count 
X = df[['duration', 'month', 'poutcome', 'contact', 'day']]
y = df['y'].map({'yes':1, 'no':0})

categorical_features = X.select_dtypes(include=['object']).columns.tolist()
numerical_features = X.select_dtypes(exclude='object').columns.tolist()

from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer

preprocessor = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), numerical_features), 
        ('cat', OneHotEncoder(handle_unknown='ignore', sparse_output=False), categorical_features)
    ]
)

/var/folders/9_/hpdl1k6s4f174xlr8mvpqt7r0000gn/T/ipykernel_39048/1433691474.py:8: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_features = X.select_dtypes(include=['object']).columns.tolist()


In [7]:
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier 

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [8]:
#random forest 
rf_classifier = Pipeline(steps=[
    ('preprocessor', preprocessor), 
    ('rf', RandomForestClassifier(n_estimators=100, random_state=42))
])

rf_classifier.fit(X_train, y_train)
y_pred_rf = rf_classifier.predict(X_test)

#evaluate
accuracy_rf = accuracy_score(y_test, y_pred_rf)
cm_rf = confusion_matrix(y_test, y_pred_rf)
classification_report_rf = classification_report(y_test, y_pred_rf)

print(f"Random Forest Accuracy: {accuracy_rf:.4f}")
print(f"Random Forest Confusion Matrix:\n{cm_rf}")
print(f'\nClassification Report:\n{classification_report_rf}')

Random Forest Accuracy: 0.8949
Random Forest Confusion Matrix:
[[7555  397]
 [ 553  538]]

Classification Report:
              precision    recall  f1-score   support

           0       0.93      0.95      0.94      7952
           1       0.58      0.49      0.53      1091

    accuracy                           0.89      9043
   macro avg       0.75      0.72      0.74      9043
weighted avg       0.89      0.89      0.89      9043



In [9]:
#support vector machine 
svm_rbf = Pipeline(steps=[
    ('preprocessor', preprocessor), 
    ('svm', SVC(kernel='rbf', random_state=42))
])

svm_rbf.fit(X_train, y_train)
y_pred_svm_rbf = svm_rbf.predict(X_test)

#evaluate 
accuracy_svm_rbf = accuracy_score(y_test, y_pred_svm_rbf)
cm_svm_rbf = confusion_matrix(y_test, y_pred_svm_rbf)
class_rep_svm_rbf = classification_report(y_test, y_pred_svm_rbf)

print(f'SVM (RBF Kernel) Accuracy: {accuracy_svm_rbf:.4f}')
print(f'\nConfusion Matrix:\n{cm_svm_rbf}')
print(f'\nClassification Report:\n{class_rep_svm_rbf}')

SVM (RBF Kernel) Accuracy: 0.9068

Confusion Matrix:
[[7744  208]
 [ 635  456]]

Classification Report:
              precision    recall  f1-score   support

           0       0.92      0.97      0.95      7952
           1       0.69      0.42      0.52      1091

    accuracy                           0.91      9043
   macro avg       0.81      0.70      0.73      9043
weighted avg       0.90      0.91      0.90      9043



In [10]:
#K-nearest neighbors
knn_classifier = Pipeline(steps=[
    ('preprocessor', preprocessor), 
    ('knn', KNeighborsClassifier(n_neighbors=5))
])

knn_classifier.fit(X_train, y_train)
y_pred_knn = knn_classifier.predict(X_test)

#evaluate
accuracy_knn = accuracy_score(y_test, y_pred_knn)
cm_knn = confusion_matrix(y_test, y_pred_knn)
class_rep_knn = classification_report(y_test, y_pred_knn)

print(f'KNN Accuracy: {accuracy_knn:.4f}')
print(f'\nConfusion Matrix:\n{cm_knn}')
print(f'\nClassification Report:\n{class_rep_knn}')

KNN Accuracy: 0.8982

Confusion Matrix:
[[7608  344]
 [ 577  514]]

Classification Report:
              precision    recall  f1-score   support

           0       0.93      0.96      0.94      7952
           1       0.60      0.47      0.53      1091

    accuracy                           0.90      9043
   macro avg       0.76      0.71      0.74      9043
weighted avg       0.89      0.90      0.89      9043

